export const userInputs = [{
        id: 1,
        label: "Prénom",
        name: "FirstName",
        type: "text",
        placeholder: "Louis",
    },
    {
        id: 2,
        label: "Nom",
        name: "LastName",
        type: "text",
        placeholder: "Dubois",
    },
    {
        id: 3,
        label: "Email",
        name: "Email",
        type: "mail",
        placeholder: "louis_dubois@gmail.com",
    },
    {
        id: 4,
        label: "N° Téléphone",
        name: "Phone",
        type: "text",
        placeholder: "0123456789",
    },
    {
        id: 5,
        label: "Mot de passe",
        name: "password",
        type: "password",
    },
    {
        id: 6,
        label: "Adresse 1",
        name: "Address1",
        type: "text",
        placeholder: "Av. des Champs-Élysées",
    },
    {
        id: 7,
        label: "Adresse 2",
        name: "Address2",
        type: "text",
        placeholder: "",
    },
    {
        id: 8,
        label: "Adresse 3",
        name: "Address3",
        type: "text",
        placeholder: "",
    },
    {
        id: 9,
        label: "Code Postal",
        name: "postCode",
        type: "text",
        placeholder: "75008 ",
    },
    {
        id: 10,
        label: "Ville",
        name: "city",
        type: "text",
        placeholder: "Paris",
    },
];